name: Update Events JSON

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-ical

      - name: Build events.json from ICS feeds
        run: |
          node .github/scripts/fetch-events-from-ics.js \
            "https://www.romeoville.org/common/modules/iCalendar/iCalendar.aspx?catID=46&feed=calendar" \
            "https://www.romeoville.org/common/modules/iCalendar/iCalendar.aspx?catID=14&feed=calendar"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add events.json
          git commit -m "Update events.json (ICS merge) [skip ci]" || echo "No changes to commit"
          git push
